stages:
  - preparation
  - staging
  - integration-tests
  - deploy


image: docker:19.03
services:
  - docker:19.03-dind


before_script:
  - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY


unit-tests:
  stage: preparation
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/utest:$CI_COMMIT_REF_SLUG
  script:
    - docker build -t $IMAGE_TAG -f build/container-image-utest/Dockerfile .
    - docker push $IMAGE_TAG
    - docker run $IMAGE_TAG


build:
  stage: preparation
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker build --pull -t $IMAGE_TAG -f ./build/container-image/Dockerfile .
    - docker push $IMAGE_TAG


integration-tests:
  stage: integration-tests
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/itest:$CI_COMMIT_REF_SLUG
  script:
    - echo todo


deploy_stage:
  stage: deploy
  environment:
    name: stage
    url: https://stage.webgrinch.8qfx1ai5.de
  script:
    - echo todo
  only:
    - master

  
deploy_prod:
  stage: deploy
  environment:
    name: production
    url: https://stage.webgrinch.8qfx1ai5.de
  script:
    - echo todo
  when: manual
  only:
    - master


deploy_review:
  stage: deploy
  environment:
      name: review/$CI_COMMIT_REF_SLUG
      url: https://$CI_COMMIT_REF_SLUG.stage.webgrinch.8qfx1ai5.de
  script:
    - echo todo
  only:
    - merge_requests
