stages:
  - build & test

docker-utest:
  image: docker:latest
  stage: build & test
  services:
    - docker:dind
  script:
    - docker build -t "$CI_COMMIT_REF_SLUG_utest" -f build/container-image-utest/Dockerfile .
    - docker run "$CI_COMMIT_REF_SLUG_utest"

docker-build-master:
  image: docker:latest
  stage: build & test
  services:
    - docker:dind
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" -f ./build/container-image/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master


docker-build:
  # Official docker image.
  image: docker:latest
  stage: build & test
  services:
    - docker:dind
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -f ./build/container-image/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
